[webservers]
web01 ansible_host=34.202.236.150 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/Joao-useast1.pem
web02 ansible_host=54.159.252.173 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/Joao-useast1.pem

[dbservers]
db01 ansible_host=54.227.4.20 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/Joao-useast1.pem